> TOC
```
Step 1. 단일 데이터 표현
     1-1. int
     1-2. float
     1-3. str
     1-4. bool
Step 2. 다중 데이터 표현
     2-1. list
     2-2. dict
     2-3. set
Step 3. 벡터 및 행렬 표현
     3-1. (numpy)array
     3-2. (pandas)DataFrame, Series
```

## Step 1. 단일 데이터 표현

### 1-1. int

In [1]:
a = 1
b = 2

In [2]:
print(a)

1


In [3]:
type(a)

int

In [4]:
print(a + b)

3


In [5]:
type(a + b)

int

### 1-2. float

In [6]:
c = 0.1
d = 0.3

In [7]:
print(c)

0.1


In [8]:
type(c)

float

In [9]:
print(c + d)

0.4


In [10]:
type(c + d)

float

In [11]:
print(int(c + d))

0


In [12]:
type(int(c + d))

int

In [13]:
print(c + d + 0.6)

1.0


In [14]:
type(c + d + 0.6)

float

In [15]:
print(int(c + d + 0.6))

1


In [16]:
type(int(c + d + 0.6))

int

### 1-3. str

In [17]:
print(a)
print(b)

1
2


In [18]:
str(a)

'1'

In [19]:
# Question
print(str(a) + str(b))

12


In [20]:
e = 'something'
f = ''

In [21]:
print(e)

something


In [22]:
type(e)

str

In [23]:
print(f)

In [24]:
type(f)

str

### 1-4. bool

In [25]:
g = True
h = False

In [26]:
print(g)

True


In [27]:
type(g)

bool

In [28]:
print(int(g))
print(int(h))

1
0


In [29]:
print(g + h)

1


In [30]:
type(g + h)

int

In [31]:
print(e)
print(f)

something



In [32]:
bool(e)

True

In [33]:
bool(f)

False

In [34]:
print(e + f)

something


In [35]:
print(bool(e) + bool(f))

1


In [36]:
type(bool(e) + bool(f))

int

## Step 2. 다중 데이터 표현

### 2-1. list

In [37]:
li_a = [1, 2, 3]
li_b = [4, 5, 6]

In [38]:
print(li_a)

[1, 2, 3]


In [39]:
# Question
print(li_a + li_b)

[1, 2, 3, 4, 5, 6]


In [82]:
# Question
print(li_a + li_b + ['else'])

[1, 2, 3, 4, 5, 6, 'else']


In [83]:
list('else')

['e', 'l', 's', 'e']

### 2-2. dict

In [40]:
dict_ab = {
    "a": li_a,
    "b": li_b
}

In [41]:
print(dict_ab)

{'a': [1, 2, 3], 'b': [4, 5, 6]}


In [42]:
print(dict_ab['a'])

[1, 2, 3]


In [43]:
print(dict_ab['b'])

[4, 5, 6]


In [44]:
print(dict_ab['a'] + dict_ab['b'])

[1, 2, 3, 4, 5, 6]


### 2-3. set

In [45]:
set_a = {1, 2, 3}
set_b = {2, 3, 4}

In [46]:
type(set_a)

set

In [47]:
# 교집합, and
print(set_a & set_b)

{2, 3}


In [48]:
# 합집합, or
print(set_a | set_b)

{1, 2, 3, 4}


In [49]:
# 차집합
print(set_a - set_b)

{1}


In [50]:
list_c = [1,2,2,3,3,4,5]

In [51]:
print(list_c)

[1, 2, 2, 3, 3, 4, 5]


In [52]:
print(set(list_c))

{1, 2, 3, 4, 5}


## Step 3. 벡터 및 행렬 표현

### 3-1. numpy array

In [53]:
import numpy as np

In [54]:
np_a = np.array([1,2,3])
np_b = np.array([4,5,6])

In [55]:
print(np_a)

[1 2 3]


In [56]:
print(np_a + np_b)

[5 7 9]


In [57]:
print(np_a * np_b)

[ 4 10 18]


In [58]:
print(np.dot(np_a, np_b))
# 4 + 10 + 18 

32


In [61]:
np_a.shape

(3,)

In [62]:
np_b.shape

(3,)

In [66]:
print(np.array([np_a, np_b]))

[[1 2 3]
 [4 5 6]]


In [67]:
np.array([np_a, np_b]).shape

(2, 3)

### 3-2. pandas DataFrame, Series

In [59]:
import pandas as pd

In [68]:
df = pd.DataFrame(data={
    'a': np_a,
    'b': np_b
})

In [ ]:
display(df)

a  b
0  1  4
1  2  5
2  3  6

In [73]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df['a']

0    1
1    2
2    3
Name: a, dtype: int64

In [77]:
type(df['a'])

pandas.core.series.Series

In [80]:
df.sum(axis=0)

a     6
b    15
dtype: int64

In [79]:
df.sum(axis=1)

0    5
1    7
2    9
dtype: int64