## Step 1. Data type

### 1-1. int, str

In [ ]:
a = 1
b = 2

In [ ]:
print(a)

1


In [ ]:
print(a + b)

3


In [ ]:
# Question
print(str(a) + str(b))

12


### 1-2. list, dict

In [ ]:
li_a = [1, 2, 3]
li_b = [4, 5, 6]

In [ ]:
print(li_a)

[1, 2, 3]


In [ ]:
# Question
print(li_a + li_b)

[1, 2, 3, 4, 5, 6]


In [ ]:
dict_ab = {
    "a": li_a,
    "b": li_b
}

In [ ]:
print(dict_ab)

{'a': [1, 2, 3], 'b': [4, 5, 6]}


In [ ]:
print(dict_ab['a'])

[1, 2, 3]


In [ ]:
print(dict_ab['b'])

[4, 5, 6]


In [ ]:
print(dict_ab['a'] + dict_ab['b'])

[1, 2, 3, 4, 5, 6]


### 1-3. numpy array, pandas dataframe

In [ ]:
import numpy as np

In [ ]:
np_a = np.array([1,2,3])
np_b = np.array([4,5,6])

In [ ]:
print(np_a)

[1 2 3]


In [ ]:
print(np_a + np_b)

[5 7 9]


In [ ]:
print(np_a * np_b)

[ 4 10 18]


In [ ]:
print(np.dot(np_a, np_b))
# 4 + 10 + 18 

32


In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(data={
    'a': np_a,
    'b': np_b
})

In [ ]:
print(df)

   a  b
0  1  4
1  2  5
2  3  6


In [ ]:
display(df)

a  b
0  1  4
1  2  5
2  3  6

In [ ]:
df
# 행(row) 열(column)

a  b
0  1  4
1  2  5
2  3  6